### ISSUE TITLE
object extraction fails with `const`

### ISSUE THREAD

**Issue by j4k0xb** [MichaelXF/js-confuser#106]
**Describe the bug:**

object extraction of a `const` variable errors at runtime

**Config and Small code sample**

Config:

```js
{
  compact: true,
  identifierGenerator: 'randomized',
  objectExtraction: true,
  target: 'browser',
}
```

Code:

```js
const obj = {prop: 0};
obj.prop = 1;
console.log(obj.prop);
```

**Expected behavior**

The program should output `1`

**Actual behavior**

`TypeError: Assignment to constant variable.`

obfuscated code:
```js
const obj_prop=0;!(obj_prop=1,console['log'](obj_prop))
```

**Additional context**

an easy fix would probably be to convert the declaration to let or var

**Comment by MichaelXF** [comment]
Great find, will fix this for next release.

**Comment by j4k0xb** [comment]
just found an edge case: `const` can only be safely converted to `let` instead of `var` because of closures:
```js
for (let i = 0; i < 3; i++) {
  const obj = { prop: i };

  setTimeout(() => {
    console.log(obj.prop); // outputs 0, 1, 2
  }, 100);
}
```
after obfuscation: `2, 2, 2`

**Comment by MichaelXF** [comment]
I will get to work on this
