### ISSUE TITLE
SyntaxError: 'return' outside of function (3:4)

### ISSUE THREAD

**Issue by batongprodt** [MichaelXF/js-confuser#121]
SyntaxError: 'return' outside of function (3:4)

var base_url = window.location.host;
if (base_url != "example.com")
    return;
Why did the error occur?

**Comment by Le0Developer** [comment]
you can only return inside a function, which you do not have.

use an IIFE:
```js
(() => {
  var base_url = window.location.host;
  if (base_url != "example.com")
    return;
})();
```

**Comment by younes-zeboudj** [comment]
js-obfuscator supports `return` outside a function, it should be possible to do it, and it is useful, I am dealing with a use case where I need it

**Comment by Le0Developer** [comment]
Parse the AST yourself with acorn and add the `allowReturnOutsideFunction` like described in https://github.com/acornjs/acorn/issues/86

**Comment by MichaelXF** [comment]
Closing for now. Possible with the method [`JSConfuser.obfuscateAST(AST, options)
`](https://new--confuser.netlify.app/docs/getting-started/usage#jsconfuser-obfuscateast-ast-options)
