### ISSUE TITLE
Dynamic Text Encryption

### ISSUE THREAD

**Issue by reg499** [MichaelXF/js-confuser#139]
Hi,

I would like to request a new feature for the Js-Confuser library. While the library is highly effective in code obfuscation, I would like to suggest an additional feature that would further enhance text protection.

Specifically, I propose adding a feature that dynamically encrypts static text and then decrypts it during runtime. This could involve methods such as encoding text into ASCII values or other similar techniques. The goal would be to make the text more complex and unreadable within the code, preventing direct understanding of sensitive information.

**Example:**
```javascript
// Input
function print(x){
  console.log(x);
}

print("Hello World");

// Output
function decodeMessage(encoded) {
return String.fromCharCode(...encoded);
}

function print(x){
  console.log(x);
}

const encodedMessage = [72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100]; // ASCII values
print(decodeMessage(encodedMessage));
```

This feature would be particularly beneficial for developers looking to protect sensitive text. The encryption and decryption process could be implemented as an additional function or integrated with existing obfuscation techniques.

I hope you will consider this request and evaluate the possibility of including this feature in future updates.

Thank you,

**Comment by doctor8296** [comment]
I think this obfuscator already does this

**Comment by MichaelXF** [comment]
`String Concealing` is the option you're looking for. In the 2.0 rewrite (which is coming soon), you'll be able to customize the string encoding functions to your own.

**Comment by MichaelXF** [comment]
Introduced in 2.0. (Currently [2.0.0-alpha.3](https://www.npmjs.com/package/js-confuser/v/2.0.0-alpha.3))

https://new--confuser.netlify.app/docs/options/customstringencodings#custom-string-encodings

**Comment by MichaelXF** [comment]
Added in 2.0.
