### ISSUE TITLE
Property renaming

### ISSUE THREAD

**Issue by doctor8296** [MichaelXF/js-confuser#140]
That's it we need that xD

**Comment by MichaelXF** [comment]
Not planned. Too error-prone. It would most likely struggle with dynamic keys, just like [Obfuscator.io's `renameProperties`](https://github.com/javascript-obfuscator/javascript-obfuscator?tab=readme-ov-file#renameproperties)  (even on 'safe' mode):

```js
// Input
(function () {
    const foo = {
        prop1: 1,
        prop2: 2,
        calc: function () {
            return this.prop1 + this.prop2;
        },
    };

    function doStuffWithFoo(foo) {
        var calc = "cal" + "c";
        console.log(foo[calc]());
    }

    doStuffWithFoo(foo);
})();
// 3

// Output
(function () {
    const _0x1ded56 = {
        '_0x7aa8af': 0x1,
        '_0x204e8e': 0x2,
        '_0x3d83a6': function () {
            return this['_0x7aa8af'] + this['_0x204e8e'];
        }
    };
    function _0x19b102(_0x420ffb) {
        var _0x643b75 = 'cal' + 'c';
        console['log'](_0x420ffb[_0x643b75]());
    }
    _0x19b102(_0x1ded56);
}());
// Uncaught TypeError: _0x18422a[_0x4ce7a3] is not a function
```

`Object Extraction` is safe alternative that can be used to rename property names by first converting them to individual variables.

Unless there is a concrete way to safely replace property names then I won't risk adding it. PRs are welcome to implement it.

**Comment by Mrgaton** [comment]
if values are static this could be posible if you pre evaluate all string conversions but it woudl be horrible to implement plus if it acces a property from for example a http request or something that is not in the code itself would be imposible.

**Comment by doctor8296** [comment]
I mean, if you could connect to typescript somehow you will probably somehow be able to rename it ... probably

**Comment by Le0Developer** [comment]
Use https://developers.google.com/closure/compiler/ and then obfuscate the generated JS code. Pretty sure reCAPTCHA is doing this.

**Comment by MichaelXF** [comment]
Not planned, but pull requests are welcome.
