### ISSUE TITLE
Shuffle option causes Antiviruses to find Trojan

### ISSUE THREAD

**Issue by Limbo2332** [MichaelXF/js-confuser#146]
**Describe the bug:**

For example, use https://www.virustotal.com/gui/home/upload to check for viruses through obfucsated javascript files. With shuffle: "hash" configuration it finds the viruses stably. 

**Config and Small code sample**

Config:

```js
{
      target: "browser",
      preset: "high",
      renameVariables: false,
      renameGlobals: false,
      minify: false,
      controlFlowFlattening: false,
      deadCode: false,
      flatten: false,
      shuffle: { hash: 0.5, true: 0.5 } (any value that contains hash) 
}
```

**Expected behavior**

There are no viruses found in obfuscated code.

**Actual behavior**

There are viruses found in obfuscated code.

**Additional context**

I don't know if it would be helpful, but similar problem with javascript-obfuscator package described here: https://github.com/javascript-obfuscator/javascript-obfuscator/issues/51

**Comment by Limbo2332** [comment]
Version I use: 1.7.1

**Comment by Limbo2332** [comment]
Without "shuffle" option in Obfuscator configuration I cannot reproduce this issue.

**Comment by MichaelXF** [comment]
It's hard to control when Antiviruses decide to flag. Sometimes they flag when the code simply looks obfuscated (hexadecimal variables, encrypted strings, etc). Also, the shuffle: "hash" option is removed in 2.0 (currently [2.0.0-alpha.2](https://www.npmjs.com/package/js-confuser/v/2.0.0-alpha.2))

I would suggest not using the shuffle: "hash" option, it's not a powerful obfuscation after all.

**Comment by MichaelXF** [comment]
Closing for now
