### ISSUE TITLE
data written with backtrick is not encrypted.

### ISSUE THREAD

**Issue by slush3** [MichaelXF/js-confuser#149]
Hi. js-confuser ``(Backtick)  does NOT encrypt console messages written in it.

**Example**

Input: 

```javascript
console.log(`Hello World!`);
```

Output: ```
... var smccs9,EbRN91F,Xxc9B0B=function(...gVwlCX){typeof(gVwlCX['length']=0,gVwlCX['a4fNOkB']=gVwlCX['\u0044\u0074\u004d\u007a\u0035\u0038'],gVwlCX['a4fNOkB']=[LJ8l61(11)]);var _3UvFkQ=function(...gVwlCX){void(gVwlCX['\u006c\u0065\u006e\u0067\u0074\u0068']=0,gVwlCX[124]=15,gVwlCX[0]={['R3JYYe']:LJ8l61(9)},gVwlCX[131]=gVwlCX[0]);try{return global||window||new Function(gVwlCX[131]['R3JYYe']+LJ8l61(10))()}catch(e){return mMxuDPp[LJ8l61['call'](undefined,11)](this)}};var mMxuDPp=function(){try{return this}catch(e){return null}};return EbRN91F=mMxuDPp['\x63\x61\x6c\x6c'](this,QewAEgq),smccs9=_3UvFkQ[gVwlCX['\u0061\u0034\u0066\u004e\u004f\u006b\u0042'][0]](this)}[ahTfcBY]();void(QewAEgq(-56)[LJ8l61(12)]  --->   (`Hello World!`)  <---   ,LkUZcOF(QewAEgq,1)); ...```

I don't know if this is a problem or this is not specified in the code. But I hope it will be fixed in the new update. 

Thank you.

**Comment by MichaelXF** [comment]
Hi, this will be solved in 2.0. (Currently [2.0.0-alpha.2](https://www.npmjs.com/package/js-confuser/v/2.0.0-alpha.2))

[Demo](https://new--confuser.netlify.app/editor?code=console.log%28%60Hello+World%60%29%3B%0A&config=%2F%2F+This+file+is+evaluated+as+JavaScript.+You+can+use+JavaScript+here.%0A%2F%2F+Learn+more%3A+https%3A%2F%2Fjs-confuser.com%2Fdocs%2Fgetting-started%2Fplayground%23jsconfuser-ts%0A%0Amodule.exports+%3D+%7B%0A++target%3A+%27node%27%2C%0A++preset%3A+%27low%27%2C%0A++stringConcealing%3A+true%2C%0A%7D%3B%0A)

**Comment by MichaelXF** [comment]
Fixed in 2.0.
