### ISSUE TITLE
EVAL

### ISSUE THREAD

**Issue by Aslarex** [MichaelXF/js-confuser#159]
Is there a way to avoid using eval in the obfuscated code?

**Comment by Aslarex** [comment]
Ahh nevermind, i had "Tamper Protection" option checked

**Comment by MichaelXF** [comment]
Eval can be avoided by disabling/not using `pack`, `rgf`, and `lock.tamperProtection`

**Comment by Aslarex** [comment]
How about avoiding setting global variables? I do not want to set any additional object on window

**Comment by MichaelXF** [comment]
You can use the `pack` option or manually 'pack' the code yourself with an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE):

```js
(function(){
   // Obfuscated code here
})()
```
