### ISSUE TITLE
The Ability to be Able to DeConfuse lost Code

### ISSUE THREAD

**Issue by AstroX11** [MichaelXF/js-confuser#166]
**Is your feature request related to a problem? Please describe.**
Look common it's possible one could lose their code, man create DeConfuser for this

**Comment by PixelMelt** [comment]
this defeats the purpose of obfuscation in the first place, if you would like an easily reversable method of encoding your program I recommend [roadroller](https://lifthrasiir.github.io/roadroller/)

**Comment by AstroX11** [comment]
> @AstroX11 this is ridiculous to do deobfuscator for obfuscator. Also there is no possible case to loose anything

Gosh

**Comment by AstroX11** [comment]
> this defeats the purpose of obfuscation in the first place, if you would like an easily reversable method of encoding your program I recommend [roadroller](https://lifthrasiir.github.io/roadroller/)

Thanks
