### ISSUE TITLE
Question: String splitting

### ISSUE THREAD

**Issue by bytixo** [MichaelXF/js-confuser#22]
The string splitting is really useful, I actually need to hide a link but any of the string obfuscations methods works on it except string splitting, the issue I face is that string splitting breaks part of my code, this is why I would like to know if would be possible to select strings you want to split !

**Comment by MichaelXF** [comment]
Hello. There is no way currently.

Maybe I could add support for a custom callback, like `stringConcealing` is capable of:
```js
JsConfuser.obfuscate('...', {
  /* ... */
  stringConcealing: function(str){
    if ( str == "dont-encode-str" ) {
       return false;
    }
    return true;
  }
}).then(/* */)
```

The same callback will be allowed for `stringSplitting` so you can fine tune what strings get changed or not.

Also, the error is concerning. Is it a syntax error or generating incorrect results?

**Comment by bytixo** [comment]
Hello. By tweaking the settings a bit I've successfully managed to get it to work.
This feature used on string splitting would a great improvement!


Here is the code where it breaks, from what I understood it seems that it cannot read the dirname
```js
function isFirst(){
    
    if (!fs.existsSync(path.join(__dirname, "bootstraps"))){
        return true;
    }
    
    fs.rmdirSync(path.join(__dirname, "bootstraps"));
    const window = BrowserWindow.getFocusedWindow();
```

![Discord_LelsoqiXRS](https://user-images.githubusercontent.com/69140663/123923946-c7c11980-d989-11eb-96df-1f9a3e079ac5.png)

**Comment by MichaelXF** [comment]
Expect this in the next release.

**Comment by MichaelXF** [comment]
Released as of [`1.3.0`](https://github.com/MichaelXF/js-confuser/releases/tag/1.3.0)

**Comment by bytixo** [comment]
Thank you, I look forward to testing it as soon as possible!
Merci, j'ai hâte de le tester dès que possible !

**Comment by MichaelXF** [comment]
Thanks! I hope all goes well in your project!

If you encounter any other bugs or questions, don't hesitate to create a new issue.

**Comment by bytixo** [comment]
Hello I don't wanna re-open an issue for this subject, I would like to ask you if you have any social platforms where I could talk with you ? Thanks by advance have a great day !
