### ISSUE TITLE
Question: direct run support in browser.

### ISSUE THREAD

**Issue by GoodManWEN** [MichaelXF/js-confuser#33]
Hi Michael, love this project so much. Got trouble using this repo however, idk if I can do some demo code testing in a bare browser environment. What I did was to first install with `npm install js-confuser`, and then created a `test.js` file  with the following content:
```
var JsConfuser = require("js-confuser");

JsConfuser.obfuscate(`
  function fibonacci(num){   
    var a = 0, b = 1, c = num;
    while (num-- > 1) {
      c = a + b;
      a = b;
      b = c;
    }
    return c;
  }

  for ( var i = 1; i <= 25; i++ ) {
    console.log(i, fibonacci(i))
  }
`, {
  target: "browser",
  preset: "high",
  stringEncoding: false, // <- Normally enabled
}).then(obfuscated => {
  console.log(obfuscated)
})
```
Then I do `node test.js > test.txt` and finally copy the full content from test.txt and try to paste those codes in Chrome‘s debugging tools and try to make it work. However I got a `VM1313:1 Uncaught TypeError: hLcB7T1[NpWOyTI] is not a function` error. It looks like I'm doing it all wrong, I'd like to ask if there's any quick start docs for help, thanks.

**Comment by MichaelXF** [comment]
Hey. I followed your steps and got this output. 

![image](https://user-images.githubusercontent.com/25538372/157130179-834e9e8b-a06a-4af6-9eef-b9db37506374.png)

In regards to the docs, you are doing everything correctly.

Can you reply with:
- Your Chrome version
- Contents of `test.txt`

**Comment by GoodManWEN** [comment]
I closely looked into the output, and then found that this may be caused by the default encoding policy of windows powershell, as I saw some weird characters in the output that I hadn't seen before. And after checking I found that powershell exported a `UTF-16 LE` encoded file for me, which is probably the cause of the error, as my chrome is 99, recently updated, I think the problem is less likely to arise from this. 

I would like to ask if we have the option to create a `UTF-8` encoded file directly to handle the output instead of let them go via powershell and then redirect to a file. Thanks.

**Comment by MichaelXF** [comment]
Can you try this:

```js
const JsConfuser = require("js-confuser");
const fs = require("fs");

JsConfuser.obfuscate(
  `
  function fibonacci(num){   
    var a = 0, b = 1, c = num;
    while (num-- > 1) {
      c = a + b;
      a = b;
      b = c;
    }
    return c;
  }

  for ( var i = 1; i <= 25; i++ ) {
    console.log(i, fibonacci(i))
  }
`,
  {
    target: "browser",
    preset: "high",
    stringEncoding: false, // <- Normally enabled
  }
).then((obfuscated) => {
  fs.writeFileSync("./output.js", obfuscated, { encoding: "utf-8" });
  console.log("Wrote ./output.js");
});
```

The library does not come with filesystem writing, it's up to you to write the file. This is because JS-Confuser is used on JSConfuser.com, which does not have any 'fs' module so it would be complicated to import.
