### ISSUE TITLE
options.minify  bug

### ISSUE THREAD

**Issue by ms2146** [MichaelXF/js-confuser#34]
use minify.test.ts

 `var code = function greet(){
    if(true){
        console.log("return");
        return;
    }
    var output = "should not show!";
    console.log(output);
}
greet();`

options = { target: "browser", minify: true }

output code:

`var greet=()=>{if(!0){console.log('return')}var output='should not show';console.log(output)};greet()`

The return in the if statement is removed

**Comment by MichaelXF** [comment]
Hey, great find! I will start working on this and this will be fixed in the next version.

**Comment by MichaelXF** [comment]
Fixed in `1.4.3`

**Comment by ms2146** [comment]
Great
