### ISSUE TITLE
deconstructuring in for loop

### ISSUE THREAD

**Issue by Le0Developer** [MichaelXF/js-confuser#43]
**Describe the bug:**

It does not compile

**Config and Small code sample**

Config:

```js
{
  target: "node",
  preset: "high"
}
```

Code:

```js
// any of these will trigger the error, minimal reproduction example
for(const [] of []) {}
for(const {} of []) {}
for(const [] in []) {}
for(const {} in []) {}
```

**Expected behavior**

Should compile.

**Actual behavior**

Does not compile: `TypeError: Cannot read properties of null (reading 'type')`

**Comment by MichaelXF** [comment]
Fixed in 1.5.2, available now on NPM
