### ISSUE TITLE
return in a switch case

### ISSUE THREAD

**Issue by Le0Developer** [MichaelXF/js-confuser#44]
**Describe the bug:**

Using a return statement in a switch case causes a compilation error.

**Config and Small code sample**

Config:

```js
{
  target: "node",
  preset: "high"
}
```

Code:

```js
function() {
    switch (1) {
        case 0:
            return;
    }
}
```

**Expected behavior**

Successful obfuscation.

**Actual behavior**

Obfuscation fails with `SyntaxError: Unexpected token (1:8)`.

**Comment by MichaelXF** [comment]
The sample has a syntax error

**Comment by Le0Developer** [comment]
Oops, can't find the original code that led to this anymore.
Can't find any code to reproduce rn, so I'll close for now.
