### ISSUE TITLE
default in a switch case

### ISSUE THREAD

**Issue by Le0Developer** [MichaelXF/js-confuser#45]
**Describe the bug:**

Compilation failure.

**Config and Small code sample**

Config:

```js
{
  target: "node",
  preset: "high"
}
```

Code:

```js
switch (0) {
    default:
         console.log("hi");
}
```

**Expected behavior**

Successful compilation.

**Actual behavior**

Compilation error with `TypeError: Cannot read properties of null (reading 'type')`.

**Comment by MichaelXF** [comment]
Thank you, fixed in 1.5.4
