### ISSUE TITLE
invalid typings for options

### ISSUE THREAD

**Issue by relative** [MichaelXF/js-confuser#46]
Type defs:  https://github.com/MichaelXF/js-confuser/blob/64a5f6a269280f6b94a2fd2a55406ffa867efab2/src/options.ts#L456-L605
Assertion stmts: https://github.com/MichaelXF/js-confuser/blob/64a5f6a269280f6b94a2fd2a55406ffa867efab2/src/options.ts#L772-L823

booleans (or `false`) are specified as valid values for some of the keys in the typedefs however there are assertion statements that will error out when it doesn't receive anything other than an array.

**Comment by relative** [comment]
is this wontfix ?

**Comment by MichaelXF** [comment]
No it will be fixed next update.
