### ISSUE TITLE
Shuffle transform in shift mode breaks program

### ISSUE THREAD

**Issue by relative** [MichaelXF/js-confuser#48]
**Describe the bug:**

shuffle transform will attempt to assign to arrays that are `const`

**Config and Small code sample**

Config:

```js
{
    target: 'browser',
    shuffle: true,
    compact: false,
    minify: false,
}
```

Code:

```js
const a=[1,2,3];
```

**Expected behavior**

it shouldn't try assigning to a const

**Actual behavior**

it assigns to a const

**Additional context**
https://github.com/MichaelXF/js-confuser/blob/3ebf686af2712d690921ca6fd1d222c04091d94d/src/transforms/shuffle.ts#L150-L166

https://github.com/MichaelXF/js-confuser/blob/3ebf686af2712d690921ca6fd1d222c04091d94d/src/transforms/shuffle.ts#L173-L175

**Comment by MichaelXF** [comment]
Thank you, fixed in 1.5.3
