### ISSUE TITLE
jsconfuser.com down

### ISSUE THREAD

**Issue by PSVita-Dev** [MichaelXF/js-confuser#55]
I think you need to renew it.(its OK if you dont want to, but wanted to let you know)

**Comment by MichaelXF** [comment]
Hi thank you for reporting this. The website seems to be back but I'm not the owner of it. The Netlify version is hosted here:
https://master--hungry-shannon-c1ce6b.netlify.app/

**Comment by relative** [comment]
it's worth noting that the `jsconfuser.com` site makes a POST request to `https://api.jsconfuser.com/v1/obfuscate` to send the plain text script and obfuscated script to the server
![image](https://user-images.githubusercontent.com/59253100/236680110-1b406954-0758-4ee6-9da3-c4e00be44484.png)

<sup>they're also running the website in webpack-dev-server as **root**!!!!</sup>

**Comment by MichaelXF** [comment]
Closing for now. The new website is https://master--hungry-shannon-c1ce6b.netlify.app/
