### ISSUE TITLE
calculator applies only to +-*/

### ISSUE THREAD

**Issue by Le0Developer** [MichaelXF/js-confuser#56]
**Describe the bug:**

The calculator transformation is only applied to `+`, `-`, `*` and `/` (https://github.com/MichaelXF/js-confuser/blob/master/src/transforms/calculator.ts#L103)

However, there are a lot more operators in Javascript: `%`, `^`, `&`, `>>(>)`, `<<(<)`, `|`, `&&`, `||`, `==(=)`, `!=(=)`, `in`, ...

And some unary ones: `!`, `~`, ...

**Comment by MichaelXF** [comment]
Hi, thank you for noticing this. In the next update calculator will be buffed up to include these operators. And unary operators too.

**Comment by MichaelXF** [comment]
Released in 1.6.0

**Comment by Le0Developer** [comment]
You sure that the other binary operators are supported?

https://github.com/MichaelXF/js-confuser/blob/30e4043a8b007a002648cb71ae0aef36bb5edf2e/src/transforms/calculator.ts#L25
