### ISSUE TITLE
String concealing bug

### ISSUE THREAD

**Issue by ms2146** [MichaelXF/js-confuser#59]
Code:

```js
var code = 'var TEST_STRING = `Hello World`;console.log(TEST_STRING);';
var output = await JsConfuser(code, {
        target: "browser",
        stringCompression: true,
        stringEncoding: true,
        stringSplitting: true,
        stringConcealing: true,

    });
expect(output).not.toContain("Hello World");
```

**Actual behavior**

Error: expect(received).not.toContain(expected) // indexOf
Expected substring: not "Hello World"

**Comment by MichaelXF** [comment]
This is because String concealing only applies to normal quoted strings. This could be fixed by transpiling the template strings into regular strings. Js-Confuser already has this capability with the `es5` feature.

**Comment by ms2146** [comment]
thx
