### ISSUE TITLE
Anti Tooling breaks Symbols

### ISSUE THREAD

**Issue by MichaelXF** [MichaelXF/js-confuser#74]
**Describe the bug:**

Anti Tooling breaks Symbols

**Config and Small code sample**

Config:

```js
{
  target: "node",
  preset: "low"
}
```

Code:

```js
var sym1 = Symbol();

sym1;
sym1;
```

Output:

```js
var sym1=Symbol();+(sym1,sym1)
```

**Error:**

```
(node:32216) UnhandledPromiseRejectionWarning: TypeError: Cannot convert a Symbol value to a number
```

The Anti Tooling feature combines expressions and chooses a random unary operator (`void`, `typeof`, `-`, `!`, `+`, or `~`) which can cause errors with symbols. Anti Tooling, which currently has no option to be turned off, should not use unary operators that perform numeric conversions to avoid this error from occuring. The other operators work correctly.

**Comment by Le0Developer** [comment]
Also experiencing this with BigInt.
