### ISSUE TITLE
BigInt literals are converted to normal numbers

### ISSUE THREAD

**Issue by Le0Developer** [MichaelXF/js-confuser#79]
**Describe the bug:**

BigInt literals (like `1n`) are converted to normal numbers (`1`).

**Config and Small code sample**

Config:

```js
{
    "compact": true,
    "hexadecimalNumbers": true,
    "identifierGenerator": "randomized",
    "minify": true,
    "shuffle": "false",
    "target": "browser"
}
```

Code:

```js
console.log(1n);
```

**Expected behavior**

Compiles to `console.log(1n)`

**Actual behavior**

Compiles to `console.log(1)`

**Comment by MichaelXF** [comment]
Good find, I will start working on this now.
