### ISSUE TITLE
feat: number concealing

### ISSUE THREAD

**Issue by Le0Developer** [MichaelXF/js-confuser#93]
**Is your feature request related to a problem? Please describe.**
Instead of a single "Hexadecimal numbers" option, I'd propose a new option: number concealing.

Number concealing will replace number literals with:
- binary or hexadecimal notation (`10` will turn into `0b1010` or `0xa`)
- decimal exponential notation (for floats) (`10.1` could turn into `0.101e2`)
- simple math expressions (`10` could turn into `15 - 5`)

This option would replace the hexadecimalNumbers option, which is a breaking change.

I am currently working on a PR for this feature.

**Comment by Le0Developer** [comment]
https://github.com/MichaelXF/js-confuser/blob/30e4043a8b007a002648cb71ae0aef36bb5edf2e/CONTRIBUTING.md?plain=1#L45
That's exactly what squash merge is for :P
![image](https://github.com/MichaelXF/js-confuser/assets/40232557/e763f7af-fd9c-4d4b-81bc-99cbbdccaecb)

**Comment by Le0Developer** [comment]
jsnice, synchrony and webcrack all (partly) fail with the example from the PR: 
```js
// jsnice, full fail
let r = 1185 ^ 1221;
let pi = 31400e-4;
console["log"](Math["pow"](r, -14700 + 14702) * pi);

// synchrony, xor fail
let r = 1185 ^ 1221
let pi = 3.14
console.log(Math.pow(r, 2) * pi)

// webcrack, xor fail
let r = 1185 ^ 1221;
let pi = 3.14;
console.log(Math.pow(r, 2) * pi);
```

**Comment by Le0Developer** [comment]
I've tested more operators:

Operator | JSNice | synchrony | webcrack | deobfuscate.io
--- | --- | --- | --- | ---
`+` | x | √ | √ | √
`-` | x | √ | √ | √
`*` | x | √ | √ | √
`/` | x  | √ | √ | √
`%` | x  | x | x | √
`^` | x  | x | x | √
`\|` | x  | x | x | √
`&` | x  | x | x | √
`<<` | x  | x | x | √
`>>` | x  | x | x | √

**Comment by Le0Developer** [comment]
A few more ideas:
- abusing type coercion: `"10" / 2`
- immediately-indexed-array: `[10][0] / 2`
- immediately-indexed-object: `{a:10}.a / 2`
- immediately-executed-function: `(()=>10)() / 2`
- immediately-executed-math-function: `(a=>5*a)(2) / 2`

Current effectiveness:
Idea | synchrony | webcrack | deobfuscate.io
--- | --- | --- | ---
ATC | x | x | √
IIA | x | x | x
IIO | x | x | x
IEF | x | x | x
IEMF | x | x | x

**Comment by MichaelXF** [comment]
These are good ideas, maybe this could be expanded to more types of expressions too

**Comment by j4k0xb** [comment]
> and webcrack all (partly) fail with the example from the PR:

thats intentional in my case. its targeted towards javascript-obfuscator which only uses `*`, `+`, `-`, and shouldn't modify the rest of the code too much

but supporting xor etc is trivial: https://astexplorer.net/#/gist/63146255fa7fbfbe28cedbf776456aef/f3b70c9823cb0ed1de9e11caa18369b126b2abbe

more challenging are objects, functions, shadowing, multiple references/writes, etc

**Comment by MichaelXF** [comment]
Closing for now
