### ISSUE TITLE
Rename Variables slow obfuscation time

### ISSUE THREAD

**Issue by MichaelXF** [MichaelXF/js-confuser#95]
The `Rename Variables` is very slow! Taking over 30 seconds for 3mb file.

```js
{
    "fileName": "static/js/bundle.js",
    "obfuscatedTime": "55.2 Seconds",
    "transformationTimes": {
        "Preparation": "0.7 Seconds",
        "ObjectExtraction": "1 Seconds",
        "Dispatcher": "0.6 Seconds",
        "DeadCode": "0.1 Seconds",
        "Calculator": "0.1 Seconds",
        "ControlFlowFlattening": "1.2 Seconds",
        "OpaquePredicates": "0.4 Seconds",
        "StringConcealing": "0.5 Seconds",
        "DuplicateLiteralsRemoval": "0.8 Seconds",
        "MovedDeclarations": "6.1 Seconds",
        "RenameLabels": "0.9 Seconds",
        "Minify": "2.5 Seconds",
        "RenameVariables": "36.4 Seconds",
        "AntiTooling": "0.5 Seconds",
        "Finalizer": "0.7 Seconds"
    },
    "originalFileSize": "3mb",
    "obfuscatedFileSize": "10mb"
}
```

This is obfuscating an entire React build on Low preset. (With compact=false for fair file size comparison)

**Comment by fuzzbuck** [comment]
Hi, how to perform such test?
I am obfuscating quite a large file (1MB+) and it takes upwards of 5+ minutes to obfuscate, would like to figure out the cause.

**Comment by MichaelXF** [comment]
Hi this is from a webpack plugin I’m making, it will be available soon. Also I found a solution to the slow obfuscation times so expect this fixed in the next update.

**Comment by fuzzbuck** [comment]
Cool, I made a new PR with a progess bar which helped me figure out what is taking so long, apparently it's the NameRecycling transformation which takes upwards of 4 minutes!

**Comment by fuzzbuck** [comment]
Here is a simple benchmark I did for some other transformations:

Stack: 28 seconds
ControlFlow: 12 seconds
NameRecycling: 287 seconds !
MovedDeclarations: 182 seconds !
RenameLabels: 96 seconds

**Comment by MichaelXF** [comment]
Im planning on removing the Name Recycling option (it's a weak obfuscation, and Rename Variables already practically does this) and have rewritten Moved declarations to be more efficient.

**Comment by fuzzbuck** [comment]
> Hi this is from a webpack plugin I’m making, it will be available soon. Also I found a solution to the slow obfuscation times so expect this fixed in the next update.

Hey, has there been any updates to this? Looking to find out on my own what's taking so long, have there been any discoveries?

**Comment by MichaelXF** [comment]
Yes here's what I've achieved so far:

```js
 {
    "fileName": "static/js/bundle.js",
    "obfuscatedTime": "18.6 Seconds",
    "transformationTimes": {
        "Preparation": "0.8 Seconds",
        "ObjectExtraction": "1.1 Seconds",
        "Dispatcher": "0.5 Seconds",
        "DeadCode": "0.1 Seconds",
        "Calculator": "0.1 Seconds",
        "ControlFlowFlattening": "0.7 Seconds",
        "OpaquePredicates": "0.2 Seconds",
        "StringConcealing": "0.4 Seconds",
        "DuplicateLiteralsRemoval": "0.5 Seconds",
        "MovedDeclarations": "0.4 Seconds", // from 6.1 Seconds
        "RenameLabels": "0.5 Seconds",
        "Minify": "1.1 Seconds",
        "RenameVariables": "9.3 Seconds", // from 36.4 Seconds
        "AntiTooling": "0.3 Seconds",
        "Finalizer": "0.5 Seconds"
    },
    "originalFileSize": "3mb",
    "obfuscatedFileSize": "5mb"
},
```

I will release this soon
