### ISSUE TITLE
playground: impossible to disable compact

### ISSUE THREAD

**Issue by Le0Developer** [MichaelXF/js-confuser#99]
**Describe the bug:**

1. Go to https://js-confuser.com.
2. Disable all options in the Advanced Options menu, including "Compact"
3. Obfuscate something
4. Output is compacted and going back into the options reveals compact has been reenabled.

**Cause:**

Issue seems to be that `"compact":false` is not stored in the `jsconfuser_options` localStorage item for some reason.
Manually adding it to the localStorage item properly disables it.

**Comment by MichaelXF** [comment]
Thank you. I will get to fixing this

**Comment by MichaelXF** [comment]
This issue should be fixed now!
